# visualize_zones.py
"""
Visualization script for multi-zone simulation results
Run after main_multizone.py to generate charts
"""
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

def visualize_multizone_results():
    """Create visualizations from multi-zone simulation results"""
    
    print("📊 Loading multi-zone results...")
    
    # Load data
    try:
        # Load building simulation data (generated by simulate_building_data.py)
        results_df = pd.read_csv('building_simulation_data.csv')
        results_df['timestamp'] = pd.to_datetime(results_df['timestamp'])
        print(f"   ✅ Loaded building simulation data: {len(results_df)} records")
        
        # Calculate zone summary
        zone_summary = results_df.groupby('zone_name').agg({
            'total_consumption': 'sum',
            'grid_used': 'sum',
            'solar_used': 'sum'
        }).round(2)
        
        # Load alerts (generated by main_multizone.py)
        try:
            alerts_df = pd.read_csv('zone_alerts.csv')
            has_alerts = True
            print(f"   ✅ Loaded alerts: {len(alerts_df)} anomalies")
        except:
            has_alerts = False
            print("   ⚠️  No alerts file found (run main_multizone.py to generate)")
        
    except FileNotFoundError as e:
        print("❌ Error: building_simulation_data.csv not found!")
        print("   Run: python simulate_building_data.py")
        return
    
    # Set style
    sns.set_style("whitegrid")
    plt.rcParams['figure.figsize'] = (30, 26)
    
    # Create comprehensive dashboard
    fig = plt.figure(figsize=(30, 26))

    gs = fig.add_gridspec(4, 2, hspace=0.3, wspace=0.3)
    
    # 1. Zone Energy Consumption Comparison
    ax1 = fig.add_subplot(gs[0, :])
    zone_energy = results_df.groupby('zone_name')['total_consumption'].sum().sort_values(ascending=False)
    bars = ax1.bar(range(len(zone_energy)), zone_energy.values, color='steelblue', alpha=0.7)
    ax1.set_xticks(range(len(zone_energy)))
    ax1.set_xticklabels(zone_energy.index, rotation=45, ha='right')
    ax1.set_ylabel('Total Energy Consumption (kWh)', fontsize=12)
    ax1.set_title('Total Energy Consumption by Zone', fontsize=14, fontweight='bold')
    ax1.grid(axis='y', alpha=0.3)
    
    # Add value labels on bars
    for i, bar in enumerate(bars):
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.0f}', ha='center', va='bottom', fontsize=9)
    
    # 2. Temporal consumption patterns
    ax2 = fig.add_subplot(gs[1, 0])
    hourly = results_df.copy()
    hourly['hour'] = hourly['timestamp'].dt.hour
    hourly_by_zone = hourly.groupby(['hour', 'zone_name'])['total_consumption'].mean().reset_index()
    
    for zone in hourly_by_zone['zone_name'].unique():
        zone_data = hourly_by_zone[hourly_by_zone['zone_name'] == zone]
        ax2.plot(zone_data['hour'], zone_data['total_consumption'], 
                marker='o', markersize=3, label=zone, linewidth=2, alpha=0.7)
    
    ax2.set_xlabel('Hour of Day', fontsize=11)
    ax2.set_ylabel('Avg Consumption (kW)', fontsize=11)
    ax2.set_title('Hourly Consumption Patterns by Zone', fontsize=12, fontweight='bold')
    ax2.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
    ax2.grid(alpha=0.3)
    
    # 3. Solar vs Grid energy
    ax3 = fig.add_subplot(gs[1, 1])
    solar_vs_grid = results_df.groupby('zone_name').agg({
        'solar_used': 'sum',
        'grid_used': 'sum'
    }).sort_values('solar_used', ascending=True)
    
    x = range(len(solar_vs_grid))
    width = 0.4
    ax3.barh([i - width/2 for i in x], solar_vs_grid['solar_used'], 
            width, label='Solar', color='gold', alpha=0.8)
    ax3.barh([i + width/2 for i in x], solar_vs_grid['grid_used'], 
            width, label='Grid', color='coral', alpha=0.8)
    ax3.set_yticks(x)
    ax3.set_yticklabels(solar_vs_grid.index, fontsize=9)
    ax3.set_xlabel('Energy (kWh)', fontsize=11)
    ax3.set_title('Solar vs Grid Energy Usage', fontsize=12, fontweight='bold')
    ax3.legend(fontsize=10)
    ax3.grid(axis='x', alpha=0.3)
    
    # 4. Temperature control effectiveness
    ax4 = fig.add_subplot(gs[2, 0])
    temp_data = results_df.groupby('zone_name')['indoor_temp'].agg(['mean', 'std']).sort_values('mean')
    ax4.errorbar(range(len(temp_data)), temp_data['mean'], 
                yerr=temp_data['std'], fmt='o', markersize=8, 
                capsize=5, capthick=2, color='darkred', alpha=0.7)
    ax4.axhspan(20, 24, alpha=0.2, color='green', label='Comfort Zone')
    ax4.set_xticks(range(len(temp_data)))
    ax4.set_xticklabels(temp_data.index, rotation=45, ha='right', fontsize=9)
    ax4.set_ylabel('Temperature (°C)', fontsize=11)
    ax4.set_title('Indoor Temperature by Zone (Mean ± Std)', fontsize=12, fontweight='bold')
    ax4.legend(fontsize=10)
    ax4.grid(alpha=0.3)
    
    # 5. Anomaly detection summary
    ax5 = fig.add_subplot(gs[2, 1])
    if has_alerts and len(alerts_df) > 0:
        anomaly_counts = alerts_df.groupby('zone_name').size().sort_values(ascending=False)
        colors = ['red' if x > 2 else 'orange' if x > 1 else 'yellow' for x in anomaly_counts.values]
        bars = ax5.bar(range(len(anomaly_counts)), anomaly_counts.values, color=colors, alpha=0.7)
        ax5.set_xticks(range(len(anomaly_counts)))
        ax5.set_xticklabels(anomaly_counts.index, rotation=45, ha='right', fontsize=9)
        ax5.set_ylabel('Number of Anomalies', fontsize=11)
        ax5.set_title('Anomalies Detected by Zone', fontsize=12, fontweight='bold')
        ax5.grid(axis='y', alpha=0.3)
        
        # Add count labels
        for i, bar in enumerate(bars):
            height = bar.get_height()
            ax5.text(bar.get_x() + bar.get_width()/2., height,
                    f'{int(height)}', ha='center', va='bottom', fontsize=10, fontweight='bold')
    else:
        ax5.text(0.5, 0.5, 'No Anomalies Detected', 
                ha='center', va='center', fontsize=14, transform=ax5.transAxes)
        ax5.set_title('Anomalies Detected by Zone', fontsize=12, fontweight='bold')
    
    # 6. Cost breakdown
    ax6 = fig.add_subplot(gs[3, :])
    results_df['cost'] = results_df['grid_used'] * results_df['electricity_price'] * 0.25
    cost_by_zone = results_df.groupby('zone_name')['cost'].sum().sort_values(ascending=False)
    colors_cost = plt.cm.RdYlGn_r(cost_by_zone.values / cost_by_zone.max())
    bars = ax6.bar(range(len(cost_by_zone)), cost_by_zone.values, color=colors_cost, alpha=0.8)
    ax6.set_xticks(range(len(cost_by_zone)))
    ax6.set_xticklabels(cost_by_zone.index, rotation=45, ha='right', fontsize=10)
    ax6.set_ylabel('Total Cost ($)', fontsize=12)
    ax6.set_title('Energy Cost by Zone', fontsize=14, fontweight='bold')
    ax6.grid(axis='y', alpha=0.3)
    
    # Add cost labels
    for i, bar in enumerate(bars):
        height = bar.get_height()
        ax6.text(bar.get_x() + bar.get_width()/2., height,
                f'${height:.2f}', ha='center', va='bottom', fontsize=9, fontweight='bold')
    
    plt.suptitle('Multi-Zone University Energy Management Dashboard', 
                fontsize=16, fontweight='bold', y=0.995)
    
    # Save figure
    plt.savefig('multizone_dashboard.png', dpi=150, bbox_inches='tight')
    print("✅ Dashboard saved: multizone_dashboard.png")
    
    # Print summary statistics
    print(f"\n{'='*60}")
    print("📊 ZONE ANALYSIS SUMMARY")
    print(f"{'='*60}")
    print(f"\n🏆 Highest Consumption: {zone_energy.index[0]} ({zone_energy.values[0]:.1f} kWh)")
    print(f"💚 Lowest Consumption: {zone_energy.index[-1]} ({zone_energy.values[-1]:.1f} kWh)")
    print(f"\n💰 Most Expensive Zone: {cost_by_zone.index[0]} (${cost_by_zone.values[0]:.2f})")
    print(f"💵 Cheapest Zone: {cost_by_zone.index[-1]} (${cost_by_zone.values[-1]:.2f})")
    
    if has_alerts and len(alerts_df) > 0:
        print(f"\n⚠️  Zones with Most Anomalies: {anomaly_counts.index[0]} ({anomaly_counts.values[0]} alerts)")
    
    print(f"\n✅ Visualization complete!")
    print(f"📁 Open 'multizone_dashboard.png' to view results")

if __name__ == "__main__":
    visualize_multizone_results()
